### PR TITLE
AUDNZD-2839: Update business number for AU in footer

### PR DESCRIPTION
**Pull request by karanjthakkar**
Duplicate of #210. 

## Context
Update business number for AU in footer

### Changes
- Update business number for AU in footer

## Checklist
- [x] I have considered the impact of this change and added a [Change Classification](
https://transferwise.atlassian.net/wiki/spaces/EKB/pages/1401189673/Change+Classifications+and+Expectations) Label (`change:standard`, `change:impactful`, `change:emergency`)
- [x] Change meets or does not compromise the [Baseline Security Requirements](https://transferwise.atlassian.net/wiki/spaces/EKB/pages/434929973/Baseline+Security+Requirements)

### CODE REVIEW

**Comment by karanjthakkar** [comment]
Pending a test 7.x release:

https://app.circleci.com/pipelines/github/transferwise/public-navigation/641/workflows/77b176ec-cd8e-4130-ae3d-e86e41b7d286

**Review by flashsphere — APPROVED** [review]

**Review by danlaush — APPROVED** [review]

**Comment by karanjthakkar** [comment]
Works as expected on 7.x release branch: https://circle.tw.ee/gh/transferwise/public-navigation/3506 (Re-releasing v7.0.5 failed because it already exists. Once this PR is merged it should create a 7.0.6 release without any problems)

**Comment by karanjthakkar** [comment]
FYI, Current state of translations for this version:

Screenshot 2020-12-03 at 01 32 04

We're still waiting on around 10 languages.

**Comment by danlaush** [comment]
I think it will be ok to release when all the core languages are translated, as the wait times on things like Swedish are much longer and not as critical.

**Comment by flashsphere** [comment]
Which ones are core languages?

**Comment by danlaush** [comment]
@flashsphere These are the ones I'm referring to https://transferwise.atlassian.net/wiki/spaces/EKB/pages/1054213243/Supported+languages There are marketing pages (or plans for marketing pages) in the other languages, like Bulgarian, Finnish Thai etc but they aren't supported company-wide with low volumes of traffic.

**Comment by karanjthakkar** [comment]
Yep. Will wait for French and Chinese HK to finish up and then will cut a release. We should be okay without Indonesian since its support is still not 100% anyway.

**Comment by karanjthakkar** [comment]
Merging this as @flashsphere confirmed we're okay with Chinese HK translations. French translations have arrived.

**Comment by karanjthakkar** [comment]
Let's hope the 7.x release works as expected 😛 🤞

**Pull request merged**
