### PR TITLE
Fix public-nav menu header padding alignment

### PR DESCRIPTION
**Pull request by bud93411**
Before:
Screenshot 2020-03-30 at 14 41 50

After:
Screenshot 2020-03-30 at 15 15 11

### CODE REVIEW

**Comment by twrdjpalmer** [comment]
After screen shot isn't showing rounded corners any more

**Comment by KarlEST** [comment]
Just to make sure: Does it only fix nav or also other dropdowns in nav?

**Comment by bud93411** [comment]
> After screen shot isn't showing rounded corners any more

Fixed 😃

**Comment by bud93411** [comment]
> Just to make sure: Does it only fix language selector or also other dropdowns in nav?

It does fix every dropdown in nav

**Pull request merged**
