### PR TITLE
Update business number for AU in footer

### PR DESCRIPTION
**Pull request by flashsphere**
## Context
Update business number for AU in footer

### Changes
- Update business number for AU in footer

## Checklist
- [x] I have considered the impact of this change and added a [Change Classification](
https://transferwise.atlassian.net/wiki/spaces/EKB/pages/1401189673/Change+Classifications+and+Expectations) Label (`change:standard`, `change:impactful`, `change:emergency`)
- [x] Change meets or does not compromise the [Baseline Security Requirements](https://transferwise.atlassian.net/wiki/spaces/EKB/pages/434929973/Baseline+Security+Requirements)

### CODE REVIEW

**Review by KarlEST — APPROVED** [review]
LGTM but let's wait for all the translations before merging

**Comment by flashsphere** [comment]
> LGTM but let's wait for all the translations before merging

Thanks. How do I check whether the translations are completed?

**Comment by KarlEST** [comment]
> > LGTM but let's wait for all the translations before merging
> 
> Thanks. How do I check whether the translations are completed?

https://crowdin.com/project/public-navigation but it's a private project so I'm not sure if you can see it. Usually it takes them ~24h to translate everything but we have seen longer times lately. If it's urgent then I would ping #translatewise that this needs to take priority.

**Review by danlaush — APPROVED** [review]

**Comment by flashsphere** [comment]
Closing this in favor of #211 so that we can release to use in homepage.

**Comment by karanjthakkar** [comment]
Keeping this PR open so that once translations for https://github.com/transferwise/public-navigation/pull/211 have arrived and its merged, we can merge this into master so we don't miss out these changes in the 8.x release.

**Pull request closed without merging**
